-- Auto-generated tu source/src/data/candidates.ts. KHONG sua tay - chay lai script gen-seed de dong bo.

CREATE TABLE IF NOT EXISTS candidates (
  id TEXT PRIMARY KEY,
  full_name TEXT NOT NULL,
  mssv TEXT NOT NULL UNIQUE,
  email TEXT NOT NULL UNIQUE,
  math_score INT NOT NULL,
  coding_score INT NOT NULL,
  regional_count INT NOT NULL,
  wf_count INT NOT NULL,
  topic_scores JSONB NOT NULL DEFAULT '{}'::jsonb,
  achievements JSONB NOT NULL DEFAULT '[]'::jsonb,
  strengths TEXT NOT NULL DEFAULT '',
  weaknesses TEXT NOT NULL DEFAULT '',
  active BOOLEAN NOT NULL DEFAULT true
);

INSERT INTO candidates
  (id, full_name, mssv, email, math_score, coding_score, regional_count, wf_count, topic_scores, achievements, strengths, weaknesses, active)
VALUES
  ('c01', 'Nguyễn Văn An', '21127001', '21127001@student.hcmus.edu.vn', 9, 6, 2, 0, '{"math":9,"number theory":8,"greedy":7,"implementation":3,"data structures":3,"binary search":3,"brute force":5,"dp":5,"graphs":4}'::jsonb, '[{"competition":"VMO (HSG Quốc gia môn Toán)","level":"Quốc gia","year":2022,"result":"Giải Ba"},{"competition":"Olympic Toán học Sinh viên Việt Nam","level":"Đại học toàn quốc","year":2024,"result":"Giải Nhì"}]'::jsonb, 'Tư duy chứng minh chặt, phát hiện công thức nhanh', 'Cài đặt còn chậm với cấu trúc dữ liệu phức tạp', true),
  ('c02', 'Trần Thị Bình', '21127002', '21127002@student.hcmus.edu.vn', 5, 9, 1, 0, '{"data structures":9,"graphs":8,"implementation":9,"binary search":6,"greedy":4,"brute force":4,"dp":4,"math":1}'::jsonb, '[{"competition":"Học sinh giỏi Tin học cấp Tỉnh/Thành phố","level":"Tỉnh/Thành phố","year":2021,"result":"Giải Nhất"},{"competition":"ICPC Vietnam Nationals","level":"Đại học toàn quốc","year":2025,"result":"Top 10"}]'::jsonb, 'Code nhanh, ít bug, quen thao tác cấu trúc dữ liệu nâng cao', 'Chưa tự tin với bài toán chứng minh toán học', true),
  ('c03', 'Lê Văn Cường', '21127003', '21127003@student.hcmus.edu.vn', 6, 8, 3, 1, '{"dp":7,"graphs":8,"binary search":8,"implementation":5,"data structures":5,"greedy":4,"brute force":4,"math":2}'::jsonb, '[{"competition":"Học sinh giỏi Tin học cấp Tỉnh/Thành phố","level":"Tỉnh/Thành phố","year":2020,"result":"Giải Nhì"},{"competition":"ICPC Regional (Asia)","level":"Đại học toàn quốc","year":2024,"result":"Top 20"}]'::jsonb, 'Xử lý bài DP/graph ổn định dưới áp lực thời gian', 'Dễ bỏ sót edge case ở bài hình học', true),
  ('c04', 'Phạm Thị Dung', '21127004', '21127004@student.hcmus.edu.vn', 8, 5, 0, 0, '{"math":8,"geometry":8,"number theory":7,"implementation":2,"data structures":2,"binary search":2,"greedy":4,"brute force":4,"dp":4,"graphs":3}'::jsonb, '[{"competition":"VMO (HSG Quốc gia môn Toán)","level":"Quốc gia","year":2021,"result":"Giải Khuyến khích"},{"competition":"Olympic Toán học Sinh viên Việt Nam","level":"Đại học toàn quốc","year":2023,"result":"Giải Ba"}]'::jsonb, 'Trực giác hình học và số học tốt', 'Cần thời gian dài hơn để hiện thực hoá ý tưởng thành code', true),
  ('c05', 'Hoàng Văn Em', '21127005', '21127005@student.hcmus.edu.vn', 4, 9, 4, 2, '{"implementation":9,"data structures":8,"two pointers":9,"binary search":6,"greedy":4,"brute force":4,"dp":4,"graphs":3}'::jsonb, '[{"competition":"Olympic Tin học Sinh viên Việt Nam — Khối Siêu Cúp","level":"Đại học toàn quốc","year":2023,"result":"Huy chương Đồng"},{"competition":"ICPC World Finals","level":"Quốc tế","year":2024,"result":"Hạng danh dự"}]'::jsonb, 'Rất dày dạn kinh nghiệm thi đấu, tốc độ code cao', 'Ít khai thác hướng giải toán học sâu', true),
  ('c06', 'Vũ Thị Phương', '21127006', '21127006@student.hcmus.edu.vn', 9, 8, 1, 0, '{"math":9,"dp":8,"graphs":8,"geometry":9,"implementation":5,"data structures":5,"binary search":5,"greedy":6,"brute force":6}'::jsonb, '[{"competition":"IOI (Olympic Tin học Quốc tế)","level":"Quốc tế","year":2021,"result":"Huy chương Đồng"},{"competition":"Olympic Tin học Sinh viên Việt Nam — Khối Chuyên","level":"Đại học toàn quốc","year":2024,"result":"Huy chương Bạc"}]'::jsonb, 'Cân bằng cả toán và cài đặt, thường đóng vai trò đầu tàu', 'Đôi khi ôm quá nhiều bài trong một buổi thi', true),
  ('c07', 'Đặng Văn Giang', '21127007', '21127007@student.hcmus.edu.vn', 3, 4, 0, 0, '{"implementation":4,"brute force":3,"data structures":1,"binary search":1,"greedy":1,"dp":1}'::jsonb, '[]'::jsonb, 'Mới bắt đầu, chăm chỉ luyện tập', 'Cả toán và cài đặt còn yếu, cần nhiều thời gian rèn thêm', true),
  ('c08', 'Bùi Thị Hoa', '21127008', '21127008@student.hcmus.edu.vn', 7, 3, 5, 0, '{"math":7,"greedy":5,"brute force":2,"dp":2,"graphs":1}'::jsonb, '[{"competition":"Học sinh giỏi Toán cấp Tỉnh/Thành phố","level":"Tỉnh/Thành phố","year":2019,"result":"Giải Ba"}]'::jsonb, 'Kinh nghiệm thi đấu dày dặn, đọc đề nhanh', 'Cài đặt còn chậm, hay bị timeout', true),
  ('c09', 'Ngô Văn Huy', '21127009', '21127009@student.hcmus.edu.vn', 2, 8, 2, 0, '{"graphs":8,"data structures":8,"dp":6,"implementation":5,"binary search":5,"greedy":2,"brute force":2}'::jsonb, '[{"competition":"Học sinh giỏi Tin học cấp Tỉnh/Thành phố","level":"Tỉnh/Thành phố","year":2020,"result":"Giải Khuyến khích"}]'::jsonb, 'Thành thạo thư viện cấu trúc dữ liệu, code sạch', 'Chưa quen các bài cần biến đổi toán học trước khi cài đặt', true),
  ('c10', 'Đỗ Thị Kim', '21127010', '21127010@student.hcmus.edu.vn', 8, 8, 6, 0, '{"math":8,"dp":8,"geometry":8,"implementation":5,"data structures":5,"binary search":5,"greedy":5,"brute force":5,"graphs":4}'::jsonb, '[{"competition":"VMO (HSG Quốc gia môn Toán)","level":"Quốc gia","year":2020,"result":"Giải Nhì"},{"competition":"Olympic Tin học Sinh viên Việt Nam — Khối Siêu Cúp","level":"Đại học toàn quốc","year":2023,"result":"Huy chương Vàng"}]'::jsonb, 'Toàn diện cả toán và cài đặt', 'Đã vượt số lần dự thi Regional cho phép theo quy định mặc định', true),
  ('c11', 'Trịnh Văn Long', '21127011', '21127011@student.hcmus.edu.vn', 9, 2, 0, 3, '{"math":9,"number theory":9,"greedy":3,"brute force":3,"dp":3,"graphs":2}'::jsonb, '[{"competition":"VMO (HSG Quốc gia môn Toán)","level":"Quốc gia","year":2018,"result":"Giải Nhất"},{"competition":"IMO (Olympic Toán học Quốc tế)","level":"Quốc tế","year":2019,"result":"Huy chương Bạc"}]'::jsonb, 'Nền tảng toán học xuất sắc, dày dạn kinh nghiệm', 'Đã vượt số lần dự thi World Finals cho phép theo quy định mặc định', true),
  ('c12', 'Lý Thị Mai', '21127012', '21127012@student.hcmus.edu.vn', 6, 6, 1, 0, '{"greedy":6,"implementation":6,"strings":6,"data structures":3,"binary search":3,"brute force":3,"dp":3,"math":2,"graphs":2}'::jsonb, '[]'::jsonb, 'Ổn định ở mức trung bình khá cho cả hai mảng', 'Chưa có điểm mạnh nổi bật để dẫn dắt đội', true),
  ('c13', 'Phan Văn Nam', '21127013', '21127013@student.hcmus.edu.vn', 3, 7, 2, 0, '{"data structures":7,"two pointers":7,"implementation":4,"binary search":4,"greedy":2,"brute force":2,"dp":2}'::jsonb, '[]'::jsonb, 'Cài đặt nhanh các bài dạng kỹ thuật hai con trỏ', 'Ít tự tin với các bài cần lập luận toán học', true),
  ('c14', 'Vương Thị Oanh', '21127014', '21127014@student.hcmus.edu.vn', 8, 4, 0, 1, '{"math":8,"geometry":7,"number theory":8,"implementation":1,"data structures":1,"binary search":1,"greedy":3,"brute force":3,"dp":3,"graphs":2}'::jsonb, '[{"competition":"VMO (HSG Quốc gia môn Toán)","level":"Quốc gia","year":2021,"result":"Giải Khuyến khích"},{"competition":"Olympic Toán học Sinh viên Việt Nam","level":"Đại học toàn quốc","year":2024,"result":"Giải Khuyến khích"}]'::jsonb, 'Phân tích bài toán hình học/số học sắc bén', 'Thời gian hiện thực hoá lời giải còn dài', true),
  ('c15', 'Tô Văn Phúc', '21127015', '21127015@student.hcmus.edu.vn', 5, 5, 1, 0, '{"implementation":5,"greedy":5,"brute force":4,"data structures":2,"binary search":2,"dp":2,"math":1,"graphs":1}'::jsonb, '[]'::jsonb, 'Đều tay ở mức cơ bản, dễ phối hợp', 'Chưa có chuyên môn sâu ở mảng nào', true),
  ('c16', 'Chu Thị Quyên', '21127016', '21127016@student.hcmus.edu.vn', 9, 9, 0, 0, '{"math":9,"dp":9,"graphs":9,"geometry":9,"implementation":6,"data structures":6,"binary search":6,"greedy":6,"brute force":6}'::jsonb, '[{"competition":"VOI (HSG Quốc gia môn Tin học)","level":"Quốc gia","year":2022,"result":"Giải Nhất"},{"competition":"Olympic Tin học Sinh viên Việt Nam — Khối Siêu Cúp","level":"Đại học toàn quốc","year":2025,"result":"Huy chương Vàng"}]'::jsonb, 'Toàn diện, thường là hạt nhân chiến thuật của đội', 'Chưa có kinh nghiệm thi Regional', true),
  ('c17', 'Đinh Văn Rin', '21127017', '21127017@student.hcmus.edu.vn', 8, 8, 1, 0, '{"graphs":8,"data structures":8,"binary search":8,"implementation":5,"greedy":5,"brute force":5,"dp":5,"math":4}'::jsonb, '[{"competition":"Học sinh giỏi Tin học cấp Tỉnh/Thành phố","level":"Tỉnh/Thành phố","year":2021,"result":"Giải Nhì"}]'::jsonb, 'Vững cả lý thuyết đồ thị và cài đặt cấu trúc dữ liệu', 'Cần cải thiện tốc độ đọc đề bài dài', true),
  ('c18', 'Mai Thị Sương', '21127018', '21127018@student.hcmus.edu.vn', 7, 9, 0, 0, '{"strings":9,"data structures":9,"constructive algorithms":8,"implementation":6,"binary search":6,"greedy":5,"brute force":5,"dp":5,"math":3,"graphs":4}'::jsonb, '[{"competition":"ICPC Vietnam Nationals","level":"Đại học toàn quốc","year":2025,"result":"Top 5"}]'::jsonb, 'Cài đặt các bài chuỗi/cấu trúc dữ liệu rất nhanh và chắc', 'Ít kinh nghiệm với bài toán game theory', true),
  ('c19', 'Kiều Văn Tài', '21127019', '21127019@student.hcmus.edu.vn', 1, 2, 0, 0, '{"implementation":2}'::jsonb, '[]'::jsonb, 'Nhiệt tình, mới tham gia luyện tập ICPC', 'Cả toán và cài đặt đều còn ở mức mới bắt đầu', true),
  ('c20', 'Dương Thị Uyên', '21127020', '21127020@student.hcmus.edu.vn', 7, 7, 3, 1, '{"math":7,"dp":7,"games":8,"number theory":7,"implementation":4,"data structures":4,"binary search":4,"greedy":4,"brute force":4,"graphs":3}'::jsonb, '[{"competition":"Olympic Tin học Sinh viên Việt Nam — Khối Chuyên","level":"Đại học toàn quốc","year":2024,"result":"Giải Ba"}]'::jsonb, 'Cân bằng tốt, đặc biệt mạnh ở bài game theory hiếm gặp', 'Chưa thử sức ở các bài hình học phức tạp', true)
ON CONFLICT (id) DO NOTHING;
